/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cocktail.machine;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.showWindow(0));
    }
    
    @Test public void testDBHasGetAllCocktails() {
        DB classUnderTest = new DB();
        assertNotNull("app should cocktails in DB", classUnderTest.getAllCocktails());
    }
    
    @Test public void testDBHasDB() {
        DB classUnderTest = new DB();
        
        assertNull("app must connect to DB", classUnderTest.connect());
    }
}
